### ISSUE TITLE
Add user registration / invitation

### ISSUE THREAD

**Issue by henry2778** [gr8seapr0o/lcorp#1]
Необходимо добавить обычную регистрацию или регистрацию по приглашению на имейл из админки

**Comment by gr8seapr0o** [comment]
Добавил

**Comment by Nickstery** [comment]
1) with(['comments' => $comments,'portfolios' => $portfolios]); -> Такую задачу решает compact
2) Для чего пусты методы в контроллере? https://github.com/gr8seapr0o/lcorp/blob/d8957735a96f68165b31de415a09736590f21a6a/app/Http/Controllers/CommentController.php#L14 https://github.com/gr8seapr0o/lcorp/blob/d8957735a96f68165b31de415a09736590f21a6a/app/Http/Controllers/CommentController.php#L98
3) Учимся лишний раз не писать else
Если уже зашли в if, то как бы никакой else не отработает и то что под ним тоже, так как внутри if есть return
http://joxi.ru/52aY9kwf47E8d2 
пункт 4.2 не критично, но лучше приучить себя сразу
https://habrahabr.ru/post/266969/
Пример в текущем проекте
https://github.com/gr8seapr0o/lcorp/blob/d8957735a96f68165b31de415a09736590f21a6a/app/Role.php#L47 https://github.com/gr8seapr0o/lcorp/blob/d8957735a96f68165b31de415a09736590f21a6a/app/User.php#L38
4) Форматирование кода GITHUB отображает так же как есть? Скобка под скобку, сложно читать код
http://joxi.ru/VrwlDqkfOP7BKm
5) Разместить на фри или не фри хостинге, нужно проклацать

**Comment by gr8seapr0o** [comment]
1. решал задачу методами laravel
2.они были автоматически добавлены laravel  при создании маршрута типа resource. Позднее думал их реализовать, но не хватило времени.
5. http://work.pr0o.com/

**Comment by gr8seapr0o** [comment]
http://work.pr0o.com/
admin:
user
123456

1 февраля 2018 г., 19:26 пользователь Victor Nikitash <
notifications@github.com> написал:
